name: Code Scanning to Issues

on:
  #  code_scanning_alert:
  #    types:
  #      - appeared
  #      - fixed
  #      - closed
  workflow_run:
    workflows: ["Code Scanning"]
    types:
      - completed
  workflow_dispatch:

permissions:
  actions: read
  checks: read
  contents: read
  issues: write
  security-events: read
  repository-projects: write

env:
  PROJECT_ID: "3"

jobs:
  alert_handling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get project column ID
        id: get_project_column_id
        run: |
          project_column_id=$(curl -s -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/projects/${{ env.PROJECT_ID }}/columns | jq '.[0].id')
          echo "project_column_id=$project_column_id" >> $GITHUB_ENV

      - name: Create/update issues from Code Scanning alerts
        uses: actions/github-script@v6
        with:
          script: |
            const columnId = "${{ env.project_column_id }}";
            const alerts = await github.rest.codeScanning.listAlertsForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });

            for (const alert of alerts.data) {
              const issueTitle = `Code Scanning Alert: ${alert.rule.name}`;
              const issueBody = `Please address the following Code Scanning alert:\n\n- [ ] ${alert.rule.description} (${alert.html_url})`;

              const issues = await github.rest.issues.listForRepo({
                owner: context.repo.owner,
                repo: context.repo.repo,
                state: "all",
                labels: ["code scanning"],
              });

              const existingIssue = issues.data.find(issue => issue.title === issueTitle);

              if (alert.state === "open") {
                if (existingIssue) {
                  await github.rest.issues.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: existingIssue.number,
                    body: issueBody,
                  });
                } else {
                  const newIssue = await github.rest.issues.create({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    title: issueTitle,
                    body: issueBody,
                    labels: ["code scanning"],
                  });
                  
                  await github.rest.projects.createCard({
                    column_id: columnId,
                    content_id: newIssue.data.id,
                    content_type: "Issue"
                  });
                }
              } else if (alert.state === "fixed" || alert.state === "dismissed") {
                if (existingIssue) {
                  await github.rest.issues.update({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    issue_number: existingIssue.number,
                    state: "closed",
                  });
                }
              }
            }

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.TF_VAR_SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
