name: Code Scanning to Issues

on:
  #  code_scanning_alert:
  #    types:
  #      - appeared
  #      - fixed
  #      - closed
  workflow_run:
    workflows: ["Code Scanning", "trivy"]
    types:
      - completed
  workflow_dispatch:

permissions:
  #actions: read
  #checks: read
  #contents: read
  #issues: write
  #security-events: read
  #repository-projects: write
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

env:
  PROJECT_NAME: infra-kanban
  REPO_OWNER: runble1
  REPO_NAME: infra

jobs:
  alert_handling:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FEATURE_DATA: ${{ github.event.inputs.feature }} # パラメータの受け渡し
        with:
          filename: .github/ISSUE_TEMPLATE.md
