name: Code Scanning to Issues

on:
  #  code_scanning_alert:
  #    types:
  #      - appeared
  #      - fixed
  #      - closed
  workflow_run:
    workflows: ["Code Scanning", "trivy"]
    types:
      - completed
  workflow_dispatch:

permissions:
  #actions: read
  #checks: read
  #contents: read
  #issues: write
  #security-events: read
  #repository-projects: write
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

env:
  PROJECT_NAME: infra-kanban
  REPO_OWNER: runble1
  REPO_NAME: infra

jobs:
  alert_handling:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Auth project
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          #gh auth refresh -s project --hostname github.com
          gh issue create --title "Issue report" --body "issues body" --repo runble1/infra --project infra-kanban

      - name: Output alerts
        run: |
          alerts=$(gh api -X GET /repos/${{ github.repository }}/code-scanning/alerts --jq '.[] | select(.status == "open")')
          echo "aaa"
          echo "$alerts"

      - name: Create issues from Code Scanning alerts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IFS=$'\n' read -ra alerts <<< "$(gh api -X GET /repos/${{ github.repository }}/code-scanning/alerts --jq '.[] | select(.status == "open")')"

          for alert in "${alerts[@]}"; do
            rule_name=$(echo "$alert" | jq -r '.rule.name')
            alert_url=$(echo "$alert" | jq -r '.html_url')

            issue_title="Code Scanning Alert: $rule_name"
            issue_body="Please address the following Code Scanning alert:\n\n- [ ] $rule_name ($alert_url)"

            existing_issue_number=$(gh issue list --label "code scanning" --search "$issue_title" --json number -q ".[0].number")

            if [[ -z "$existing_issue_number" ]]; then
              gh issue create --title "$issue_title" --body "$issue_body" --label "code scanning" --project ${{ env.PROJECT_NAME }}
            fi
          done

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          channel-id: ${{ secrets.TF_VAR_SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
