name: Code Scanning to Projects

on:
  workflow_run:
    workflows: ["Code Scanning"]
    types:
      - completed
  workflow_dispatch:

jobs:
  slack_notification:
    runs-on: ubuntu-latest
    steps:
      - name: Check
        id: fmt
        run: |
          echo "${{ job.status }}"
          echo '${{ github.event.pull_request.html_url || github.event.head_commit.url }}'
